// Generated by CoffeeScript 1.6.2
(function() {
  var q, x, xs,
    _this = this;

  q = function(x, y) {
    var s, _i, _len;

    y = y.toString();
    for (_i = 0, _len = x.length; _i < _len; _i++) {
      s = x[_i];
      if (y.indexOf(s) < 0) {
        return false;
      }
    }
    return true;
  };

  x = 1;

  while (x++) {
    xs = x.toString();
    if (q(xs, x * 6) && q(xs, x * 5) && q(xs, x * 4) && q(xs, x * 3) && q(xs, x * 2)) {
      break;
    }
  }

  console.log(x);

}).call(this);
