// Generated by CoffeeScript 1.6.2
(function() {
  var x, z,
    _this = this;

  z = function(x, y) {
    return (x * y).toString().split('').sort().join() === x.toString().split('').sort().join();
  };

  x = 1;

  while (x++) {
    if (z(x, 2) && z(x, 3) && z(x, 4) && z(x, 5) && z(x, 6)) {
      break;
    }
  }

  console.log(x);

}).call(this);
