# encoding: UTF-8

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# A. 4613732

a = 1; b = 2; total = 2
while (x = 3 * b + 2 * a) <= 4_000_000 do
  total += x; a = 2 * b + a; b = x
end
p total
